const fs = require('fs');
const path = require('path');
const { withGradleProperties, withDangerousMod } = require('@expo/config-plugins');
const { resolveJdk17Home } = require('../scripts/resolve-jdk17');

/**
 * Local Android build fixes (android/ is gitignored):
 * - Disable Gradle JDK auto-download (foojay-resolver breaks on Gradle 9)
 * - Pin JDK 17 for CMake native modules (JDK 24+ blocks System::load)
 * - Write sdk.dir when the SDK is detectable on the build machine
 */
function withAndroidBuildFix(config) {
  config = withGradleProperties(config, (config) => {
    const properties = [
      ['org.gradle.java.installations.auto-download', 'false'],
    ];

    const jdk17Home = resolveJdk17Home();
    if (jdk17Home) {
      properties.push(['org.gradle.java.home', jdk17Home]);
    }

    for (const [key, value] of properties) {
      const existing = config.modResults.find(
        (item) => item.type === 'property' && item.key === key,
      );

      if (!existing) {
        config.modResults.push({ type: 'property', key, value });
      } else {
        existing.value = value;
      }
    }

    return config;
  });

  return withDangerousMod(config, [
    'android',
    async (config) => {
      const sdkPath = resolveAndroidSdk();
      if (!sdkPath) {
        return config;
      }

      const localPropertiesPath = path.join(
        config.modRequest.platformProjectRoot,
        'local.properties',
      );
      const escapedSdkPath = sdkPath.replace(/\\/g, '\\\\');
      fs.writeFileSync(
        localPropertiesPath,
        `## Auto-generated by withAndroidBuildFix — do not commit.\nsdk.dir=${escapedSdkPath}\n`,
        'utf8',
      );

      return config;
    },
  ]);
}

function resolveAndroidSdk() {
  const fromEnv = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  if (fromEnv && fs.existsSync(path.join(fromEnv, 'platform-tools'))) {
    return fromEnv;
  }

  const home = process.env.HOME || process.env.USERPROFILE || '';
  const defaults = [
    path.join(home, 'Library', 'Android', 'sdk'),
    path.join(home, 'Android', 'Sdk'),
    process.env.LOCALAPPDATA
      ? path.join(process.env.LOCALAPPDATA, 'Android', 'Sdk')
      : undefined,
  ].filter(Boolean);

  for (const candidate of defaults) {
    if (fs.existsSync(path.join(candidate, 'platform-tools'))) {
      return candidate;
    }
  }

  return undefined;
}

module.exports = withAndroidBuildFix;
